# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions forr Azure: https://github.com/Azure/actions
# More GitHub Actions for Azure: https://github.com/Azure/actions1

name: Build and deploy Node.js app to Azure Web App - OnePoint-ui-dev1

on:
  push:
    branches:
      - rel2-dev
  workflow_dispatch:

permissions: read-all

env:
  AZURE_WEBAPP_NAME: onepoint-eun-dev # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '5.0.x' # set this to the dot net version to use

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
      
        uses: actions/setup-node@v1
        with:
          node-version: '^14.19.0'

      - name: "yarn install, build"
        run: |
          yarn
          yarn build
      - name: Confirm files
        run: |
          ls
          ls build
      # - name: npm install, build, and test
      #   run: |
      #     npm install
      #     npm run build --if-present
      #     npm run test --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      # - name: 'Deploy to Azure Web App'
      #   id: deploy-to-webapp
      #   uses: azure/webapps-deploy@v2
      #   with:
      #     app-name: 'fiber2desk-dev'
      #     slot-name: 'Production'
      #     publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B88928330F5A4EA69732332D149815AB }}
      #     package: .

      # Deploy to Azure Web apps
      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_UI_DEV  }} # Define secret variable in repository settings as per action documentation
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/onepointui'
